// <auto-generated />
namespace whris_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class accountmanagement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(accountmanagement));
        
        string IMigrationMetadata.Id
        {
            get { return "201912250655594_accountmanagement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
